# plots windows generated by WindowMakerEmu.bsim

import common.cfg as cfg
import numpy as np
import matplotlib.pyplot as plt
import ctypes
import sys
import re


def main():
    win = []
    curch = 0

    for line in sys.stdin.xreadlines():
        line = line.strip()

        m = re.match(r"^tagged DmaData 'h([0-9a-f]+)$", line)
        if m:
            word = int(m.group(1), 16)
            for i in xrange(cfg.SamplesPerWord):
                if curch == cfg.EnabledCh:
                    curch = 0
                    break
                win.append(ctypes.c_int16(word & ((1 << cfg.PaddedBits) - 1)).value)
                word >>= cfg.PaddedBits
                curch += 1

        m = re.match(r"^tagged EndMarker WindowInfo \{ " +
                     r"timestamp: 'h([0-9a-f]+), " +
                     r"size: 'h([0-9a-f]+), " +
                     r"reference: 'h([0-9a-f]+) }$", line)
        if m:
            timestamp, size, reference = tuple(int(x, 16) for x in m.groups())
            assert(len(win) == cfg.EnabledCh * size)
            win = np.array(win)
            for ch in xrange(cfg.EnabledCh):
                plt.plot(win[ch::cfg.EnabledCh], '.-', alpha=.2)
            plt.plot([size-reference, size-reference], plt.ylim(), 'k--', lw=2, alpha=.4)
            plt.show()
            win = []


if __name__ == '__main__':
    main()
